name: Environment Variable Priority

on: push

env:
    VAR_EXAMPLE: workflow-level

jobs:
    test-env:
        runs-on: ubuntu-latest

        env:
            VAR_EXAMPLE: job-level

        steps:
            - name: Step 1 - Print variable
              shell: bash
              run: |
                  echo "Step 1 value: ${VAR_EXAMPLE}"

            - name: Step 2 - Override variable
              shell: bash
              env:
                  VAR_EXAMPLE: step-level
              run: |
                  echo "Step 2 value: ${VAR_EXAMPLE}"
